default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: application
  password: qwerty123
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test